# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.1

pipelines:
  default:
    - step:
            script:
              - apt-get update && apt-get upgrade
              - docker-php-ext-install pdo_mysql
              - apt-get install python-software-properties
              - add-apt-repository ppa:ondrej/php
              - apt-get update
              - apt-get install php7.2
              - apt-get install php-pear php7.2-curl php7.2-dev php7.2-gd php7.2-mbstring php7.2-zip php7.2-mysql php7.2-xml
              - bash ./install-composer.sh
              - composer install
              - ln -f -s .env.pipelines .env
              - php artisan serve &
              - sleep 5
              - ./vendor/bin/phpunit
